@startuml
title PostgreSQL Database Schema

skinparam linetype ortho
hide circle

entity EmailAddress <<public>> {
  * **id** : STRING <<PK>>
  --
  * createdAt : TIMESTAMP
  * updatedAt : TIMESTAMP
  * email : STRING <<UNIQUE>>
}

entity PhoneNumber <<public>> {
  * **id** : STRING <<PK>>
  --
  * createdAt : TIMESTAMP
  * updatedAt : TIMESTAMP
  * phoneNumber : STRING <<UNIQUE>>
}

entity Socials <<public>> {
  * **id** : STRING <<PK>>
  --
  * createdAt : TIMESTAMP
  * updatedAt : TIMESTAMP
  * type : ENUM
  * link : STRING
}

entity Url <<public>> {
  * **id** : STRING <<PK>>
  --
  * createdAt : TIMESTAMP
  * updatedAt : TIMESTAMP
  * url : STRING <<UNIQUE>>
  markdownContent : STRING
  title : STRING
  description : STRING
  webDomainId : STRING <<FK>> <<UNIQUE>>
}

entity WebDomain <<public>> {
  * **id** : STRING <<PK>>
  --
  * createdAt : TIMESTAMP
  * updatedAt : TIMESTAMP
  * domain : STRING <<UNIQUE>>
  companyName : STRING
  companyDescription : STRING
  location : STRING
  logoUrl : STRING
}

entity Webset <<public>> {
  * **id** : STRING <<PK>>
  --
  * createdAt : TIMESTAMP
  * updatedAt : TIMESTAMP
  searchQuery : STRING
  validationCriterias : ARRAY
  enrichmentCriterias : ARRAY
  targetCount : INT
  * createdByuserId : STRING <<FK>>
  * name : STRING
}

entity WebsetRow <<public>> {
  * **id** : STRING <<PK>>
  --
  * createdAt : TIMESTAMP
  * updatedAt : TIMESTAMP
  validationData : ARRAY
  enrichmentData : ARRAY
  websetId : STRING <<FK>> <<UNIQUE>>
  * originalData : JSONB
}

entity _EmailAddressToUrl <<public>> {
  * **A** : STRING <<PK>>
  * **B** : STRING <<PK>>
  --
}

entity _PhoneNumberToUrl <<public>> {
  * **A** : STRING <<PK>>
  * **B** : STRING <<PK>>
  --
}

entity _SocialsToUrl <<public>> {
  * **A** : STRING <<PK>>
  * **B** : STRING <<PK>>
  --
}

entity _Urls <<public>> {
  * **A** : STRING <<PK>>
  * **B** : STRING <<PK>>
  --
}

entity account <<public>> {
  * **id** : STRING <<PK>>
  --
  * createdAt : TIMESTAMP
  * updatedAt : TIMESTAMP
  * accountId : STRING
  * providerId : STRING
  * userId : STRING <<FK>>
  accessToken : STRING
  refreshToken : STRING
  idToken : STRING
  accessTokenExpiresAt : TIMESTAMP
  refreshTokenExpiresAt : TIMESTAMP
  scope : STRING
  password : STRING
}

entity apikey <<public>> {
  * **id** : STRING <<PK>>
  --
  name : STRING
  start : STRING
  prefix : STRING
  * key : STRING
  * userId : STRING <<FK>>
  refillInterval : INT
  refillAmount : INT
  lastRefillAt : TIMESTAMP
  enabled : BOOL
  rateLimitEnabled : BOOL
  rateLimitTimeWindow : INT
  rateLimitMax : INT
  requestCount : INT
  remaining : INT
  lastRequest : TIMESTAMP
  expiresAt : TIMESTAMP
  * createdAt : TIMESTAMP
  * updatedAt : TIMESTAMP
  permissions : STRING
  metadata : STRING
}

entity session <<public>> {
  * **id** : STRING <<PK>>
  --
  * createdAt : TIMESTAMP
  * updatedAt : TIMESTAMP
  * expiresAt : TIMESTAMP
  * token : STRING <<UNIQUE>>
  ipAddress : STRING
  userAgent : STRING
  * userId : STRING <<FK>>
}

entity user <<public>> {
  * **id** : STRING <<PK>>
  --
  * createdAt : TIMESTAMP
  * updatedAt : TIMESTAMP
  * name : STRING
  * email : STRING <<UNIQUE>>
  * emailVerified : BOOL
  image : STRING
}

entity verification <<public>> {
  * **id** : STRING <<PK>>
  --
  createdAt : TIMESTAMP
  updatedAt : TIMESTAMP
  * identifier : STRING
  * value : STRING
  * expiresAt : TIMESTAMP
}

'Relationships
WebDomain ||--o{ Url : Url webDomainId fkey
user ||--|{ Webset : Webset createdByuserId fkey
Webset ||--o{ WebsetRow : WebsetRow websetId fkey
EmailAddress ||--|{ _EmailAddressToUrl :  EmailAddressToUrl A fkey
Url ||--|{ _EmailAddressToUrl :  EmailAddressToUrl B fkey
PhoneNumber ||--|{ _PhoneNumberToUrl :  PhoneNumberToUrl A fkey
Url ||--|{ _PhoneNumberToUrl :  PhoneNumberToUrl B fkey
Socials ||--|{ _SocialsToUrl :  SocialsToUrl A fkey
Url ||--|{ _SocialsToUrl :  SocialsToUrl B fkey
Url ||--|{ _Urls :  Urls A fkey
Url ||--|{ _Urls :  Urls B fkey
user ||--|{ account : account userId fkey
user ||--|{ apikey : apikey userId fkey
user ||--|{ session : session userId fkey

@enduml